name: drowsiness_app
description: "Real-time driver drowsiness detection using on-device CNN-LSTM inference."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.11.0+2

  # On-device TFLite inference
  tflite_flutter: ^0.12.1

  # Face detection
  google_mlkit_face_detection: ^0.11.0

  # Image processing / resizing
  image: ^4.2.0

  # Audio alert
  audioplayers: ^6.0.0

  # Haptic vibration
  vibration: ^3.2.1

  # Permissions (camera)
  permission_handler: ^11.3.1

  # State management
  provider: ^6.1.2

  # Unique session ID
  uuid: ^4.4.2

  # Settings storage
  shared_preferences: ^2.2.3

  # Local DB for trip history
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Timeline charts
  fl_chart: ^0.68.0

  # Date & time formatting
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/cnn.tflite
    - assets/models/lstm.tflite
    - assets/models/mean.npy
    - assets/models/std.npy
    - assets/sounds/alert_beep.wav
    - assets/sounds/low_vigilant_chime.wav
